### ISSUE TITLE
class cml::CamaraLucida has no member named 'get_hue_tex_ref'

### ISSUE THREAD

**Issue by noiziv5** [chparsons/ofxCamaraLucida#6]
can't get it to compile on codeblocks linux64 ofx8.4  getting that error...
